### ISSUE TITLE
WIKI

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-s-b-j#1]
Blanca Estela Valerio Rivero
Sandy Marissa Garcia Santiago
Jorge Luis Hernández Matra

https://github.com/SistemasTecTlaxiaco/CryptoStream/wiki

**Comment by Daisy-GonzalezLita12** [comment]
Excelente trabajo, obtuvieron el 28% de acuerdo a la lista de cotejo

**Comment by josealfredo79** [comment]
bien hecho y revisado..
